### ISSUE TITLE
RestApi怎么无法用404错误

### ISSUE THREAD

**Issue by sunnyWangGirl** [MaoJianwei/ONOS_LoadBalance_Routing_Forward#2]
毛同学您好，我下载的是代码1.2的版本，ONOS是2.2版本，应用安装是成功的，我想试下它的RestAPI 功能，但是在http://<controller-ip>:8181/onos/v1/docs的菜单下面没有发现Mao这个模块。直接在浏览器输入http://<controller-ip>:8181/onos/v1/Mao和http://<controller-ip>:8181/onos/Mao都是404报错，请问该怎么成功使用restAPI功能呢，我的使用方式是不是哪里有问题？

**Comment by MaoJianwei** [comment]
Hi Wang同学，

ONOS 2.x 版本应该是Go语言的微服务版本吧？这个应该只能用于ONOS 1.x版本的（Java）

需要在ONOS里启动这个应用，可以在Web GUI的Application页面启动，也可以在命令行里activate启动 :)

Mao

**Comment by MaoJianwei** [comment]
Hi Wang同学，

安装以后需要启动这个应用，可以在Web GUI的Application页面启动，也可以在命令行activate

Mao
