### ISSUE TITLE
How can switch automatically send request to controller at a fixed rate?

### ISSUE THREAD

**Issue by minziran** [MaoJianwei/ONOS_LoadBalance_Routing_Forward#3]
In my simulation, I assume switch can send requests to ONOS controller at a fixed rate. Is there any mininet method that can do that? Or is there any software that can help me? If not, the worst case is generating requests from the host side, correct? 

Thanks!

**Comment by MaoJianwei** [comment]
Hi Ziran,

It seems that this issue has little relation to this project, **ONOS_LoadBalance_Routing_Forward** :)

What kind of request do you mean?

Mao
