### ISSUE TITLE
如何编译

### ISSUE THREAD

**Issue by Amazing8** [MaoJianwei/ONOS_LoadBalance_Routing_Forward#4]
您好，当我对项目进行一些修改如何进行编译？

**Comment by MaoJianwei** [comment]
根据你的ONOS版本，参考不同的文件，将这个负载均衡路由App链接到ONOS源码中，进行编译 @Amazing8 
[modules.bzl__available_example](https://github.com/MaoJianwei/ONOS_LoadBalance_Routing_Forward/blob/1.2/modules.bzl__available_example)
[modules.defs__available_example](https://github.com/MaoJianwei/ONOS_LoadBalance_Routing_Forward/blob/1.2/modules.defs__available_example)
